// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: blockinsight7000/v1/common.proto

package blockinsight7000v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus enumerates readiness states reported by the explorer.
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNAVAILABLE HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNAVAILABLE",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNAVAILABLE": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blockinsight7000_v1_common_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_blockinsight7000_v1_common_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_common_proto_rawDescGZIP(), []int{0}
}

// ChainSelector locates a specific blockchain deployment.
type ChainSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSelector) Reset() {
	*x = ChainSelector{}
	mi := &file_blockinsight7000_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSelector) ProtoMessage() {}

func (x *ChainSelector) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSelector.ProtoReflect.Descriptor instead.
func (*ChainSelector) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ChainSelector) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *ChainSelector) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

var File_blockinsight7000_v1_common_proto protoreflect.FileDescriptor

const file_blockinsight7000_v1_common_proto_rawDesc = "" +
	"\n" +
	" blockinsight7000/v1/common.proto\x12\x13blockinsight7000.v1\"=\n" +
	"\rChainSelector\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork*\x83\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNAVAILABLE\x10\x03BaZ_github.com/goodnatureofminers/blockinsight7000-proto/pkg/blockinsight7000/v1;blockinsight7000v1b\x06proto3"

var (
	file_blockinsight7000_v1_common_proto_rawDescOnce sync.Once
	file_blockinsight7000_v1_common_proto_rawDescData []byte
)

func file_blockinsight7000_v1_common_proto_rawDescGZIP() []byte {
	file_blockinsight7000_v1_common_proto_rawDescOnce.Do(func() {
		file_blockinsight7000_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockinsight7000_v1_common_proto_rawDesc), len(file_blockinsight7000_v1_common_proto_rawDesc)))
	})
	return file_blockinsight7000_v1_common_proto_rawDescData
}

var file_blockinsight7000_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockinsight7000_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockinsight7000_v1_common_proto_goTypes = []any{
	(HealthStatus)(0),     // 0: blockinsight7000.v1.HealthStatus
	(*ChainSelector)(nil), // 1: blockinsight7000.v1.ChainSelector
}
var file_blockinsight7000_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockinsight7000_v1_common_proto_init() }
func file_blockinsight7000_v1_common_proto_init() {
	if File_blockinsight7000_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockinsight7000_v1_common_proto_rawDesc), len(file_blockinsight7000_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockinsight7000_v1_common_proto_goTypes,
		DependencyIndexes: file_blockinsight7000_v1_common_proto_depIdxs,
		EnumInfos:         file_blockinsight7000_v1_common_proto_enumTypes,
		MessageInfos:      file_blockinsight7000_v1_common_proto_msgTypes,
	}.Build()
	File_blockinsight7000_v1_common_proto = out.File
	file_blockinsight7000_v1_common_proto_goTypes = nil
	file_blockinsight7000_v1_common_proto_depIdxs = nil
}
