// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: blockinsight7000/v1/explorer.proto

package blockinsight7000v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockSummary is a lightweight representation suited for listings.
type BlockSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hash             string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height           uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	MinedAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=mined_at,json=minedAt,proto3" json:"mined_at,omitempty"`
	TransactionCount uint32                 `protobuf:"varint,4,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	SizeBytes        uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockSummary) Reset() {
	*x = BlockSummary{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSummary) ProtoMessage() {}

func (x *BlockSummary) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSummary.ProtoReflect.Descriptor instead.
func (*BlockSummary) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{0}
}

func (x *BlockSummary) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockSummary) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockSummary) GetMinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MinedAt
	}
	return nil
}

func (x *BlockSummary) GetTransactionCount() uint32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *BlockSummary) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Block contains the full block view returned by detail endpoints.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	PreviousHash  string                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Nonce         uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Difficulty    uint64                 `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Confirmations uint32                 `protobuf:"varint,8,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,9,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Weight        uint64                 `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`
	MinedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=mined_at,json=minedAt,proto3" json:"mined_at,omitempty"`
	Transactions  []*TransactionSummary  `protobuf:"bytes,12,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *Block) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *Block) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Block) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Block) GetDifficulty() uint64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Block) GetConfirmations() uint32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *Block) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Block) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Block) GetMinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MinedAt
	}
	return nil
}

func (x *Block) GetTransactions() []*TransactionSummary {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// TransactionSummary describes essential transaction data.
type TransactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Confirmations uint32                 `protobuf:"varint,2,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	TotalSats     uint64                 `protobuf:"varint,3,opt,name=total_sats,json=totalSats,proto3" json:"total_sats,omitempty"`
	FeeSats       uint64                 `protobuf:"varint,4,opt,name=fee_sats,json=feeSats,proto3" json:"fee_sats,omitempty"`
	SeenAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=seen_at,json=seenAt,proto3" json:"seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionSummary) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *TransactionSummary) GetConfirmations() uint32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *TransactionSummary) GetTotalSats() uint64 {
	if x != nil {
		return x.TotalSats
	}
	return 0
}

func (x *TransactionSummary) GetFeeSats() uint64 {
	if x != nil {
		return x.FeeSats
	}
	return 0
}

func (x *TransactionSummary) GetSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SeenAt
	}
	return nil
}

type TransactionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrevTxid      string                 `protobuf:"bytes,1,opt,name=prev_txid,json=prevTxid,proto3" json:"prev_txid,omitempty"`
	OutputIndex   uint32                 `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ValueSats     uint64                 `protobuf:"varint,4,opt,name=value_sats,json=valueSats,proto3" json:"value_sats,omitempty"`
	ScriptSig     []byte                 `protobuf:"bytes,5,opt,name=script_sig,json=scriptSig,proto3" json:"script_sig,omitempty"`
	Sequence      uint32                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInput) Reset() {
	*x = TransactionInput{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInput) ProtoMessage() {}

func (x *TransactionInput) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInput.ProtoReflect.Descriptor instead.
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionInput) GetPrevTxid() string {
	if x != nil {
		return x.PrevTxid
	}
	return ""
}

func (x *TransactionInput) GetOutputIndex() uint32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *TransactionInput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransactionInput) GetValueSats() uint64 {
	if x != nil {
		return x.ValueSats
	}
	return 0
}

func (x *TransactionInput) GetScriptSig() []byte {
	if x != nil {
		return x.ScriptSig
	}
	return nil
}

func (x *TransactionInput) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type TransactionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ValueSats     uint64                 `protobuf:"varint,3,opt,name=value_sats,json=valueSats,proto3" json:"value_sats,omitempty"`
	Spent         bool                   `protobuf:"varint,4,opt,name=spent,proto3" json:"spent,omitempty"`
	ScriptPubKey  []byte                 `protobuf:"bytes,5,opt,name=script_pub_key,json=scriptPubKey,proto3" json:"script_pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionOutput) Reset() {
	*x = TransactionOutput{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOutput) ProtoMessage() {}

func (x *TransactionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOutput.ProtoReflect.Descriptor instead.
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionOutput) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TransactionOutput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransactionOutput) GetValueSats() uint64 {
	if x != nil {
		return x.ValueSats
	}
	return 0
}

func (x *TransactionOutput) GetSpent() bool {
	if x != nil {
		return x.Spent
	}
	return false
}

func (x *TransactionOutput) GetScriptPubKey() []byte {
	if x != nil {
		return x.ScriptPubKey
	}
	return nil
}

// Transaction is a detailed on-chain transaction representation.
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	LockTime      uint32                 `protobuf:"varint,4,opt,name=lock_time,json=lockTime,proto3" json:"lock_time,omitempty"`
	Confirmations uint32                 `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	FeeSats       uint64                 `protobuf:"varint,6,opt,name=fee_sats,json=feeSats,proto3" json:"fee_sats,omitempty"`
	SeenAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=seen_at,json=seenAt,proto3" json:"seen_at,omitempty"`
	Inputs        []*TransactionInput    `protobuf:"bytes,8,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*TransactionOutput   `protobuf:"bytes,9,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{5}
}

func (x *Transaction) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Transaction) GetLockTime() uint32 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *Transaction) GetConfirmations() uint32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *Transaction) GetFeeSats() uint64 {
	if x != nil {
		return x.FeeSats
	}
	return 0
}

func (x *Transaction) GetSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SeenAt
	}
	return nil
}

func (x *Transaction) GetInputs() []*TransactionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Transaction) GetOutputs() []*TransactionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type AddressBalance struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Address           string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ConfirmedSats     uint64                 `protobuf:"varint,2,opt,name=confirmed_sats,json=confirmedSats,proto3" json:"confirmed_sats,omitempty"`
	UnconfirmedSats   uint64                 `protobuf:"varint,3,opt,name=unconfirmed_sats,json=unconfirmedSats,proto3" json:"unconfirmed_sats,omitempty"`
	TotalReceivedSats uint64                 `protobuf:"varint,4,opt,name=total_received_sats,json=totalReceivedSats,proto3" json:"total_received_sats,omitempty"`
	TotalSentSats     uint64                 `protobuf:"varint,5,opt,name=total_sent_sats,json=totalSentSats,proto3" json:"total_sent_sats,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddressBalance) Reset() {
	*x = AddressBalance{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBalance) ProtoMessage() {}

func (x *AddressBalance) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBalance.ProtoReflect.Descriptor instead.
func (*AddressBalance) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{6}
}

func (x *AddressBalance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressBalance) GetConfirmedSats() uint64 {
	if x != nil {
		return x.ConfirmedSats
	}
	return 0
}

func (x *AddressBalance) GetUnconfirmedSats() uint64 {
	if x != nil {
		return x.UnconfirmedSats
	}
	return 0
}

func (x *AddressBalance) GetTotalReceivedSats() uint64 {
	if x != nil {
		return x.TotalReceivedSats
	}
	return 0
}

func (x *AddressBalance) GetTotalSentSats() uint64 {
	if x != nil {
		return x.TotalSentSats
	}
	return 0
}

// NetworkMetadata describes a single deployable network for a coin.
type NetworkMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetadata) Reset() {
	*x = NetworkMetadata{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetadata) ProtoMessage() {}

func (x *NetworkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetadata.ProtoReflect.Descriptor instead.
func (*NetworkMetadata) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkMetadata) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NetworkMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NetworkMetadata) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// ChainMetadata documents a supported coin and optional display hints.
type ChainMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Networks      []*NetworkMetadata     `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMetadata) Reset() {
	*x = ChainMetadata{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadata) ProtoMessage() {}

func (x *ChainMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadata.ProtoReflect.Descriptor instead.
func (*ChainMetadata) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{8}
}

func (x *ChainMetadata) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *ChainMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChainMetadata) GetNetworks() []*NetworkMetadata {
	if x != nil {
		return x.Networks
	}
	return nil
}

// ListChainsRequest has no parameters and returns all supported coins.
type ListChainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsRequest) Reset() {
	*x = ListChainsRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsRequest) ProtoMessage() {}

func (x *ListChainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsRequest.ProtoReflect.Descriptor instead.
func (*ListChainsRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{9}
}

// ListChainsResponse aggregates metadata for each supported coin.
type ListChainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*ChainMetadata       `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsResponse) Reset() {
	*x = ListChainsResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsResponse) ProtoMessage() {}

func (x *ListChainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsResponse.ProtoReflect.Descriptor instead.
func (*ListChainsResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{10}
}

func (x *ListChainsResponse) GetChains() []*ChainMetadata {
	if x != nil {
		return x.Chains
	}
	return nil
}

type GetBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Chain *ChainSelector         `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	// Types that are valid to be assigned to BlockRef:
	//
	//	*GetBlockRequest_Hash
	//	*GetBlockRequest_Height
	BlockRef            isGetBlockRequest_BlockRef `protobuf_oneof:"block_ref"`
	IncludeTransactions bool                       `protobuf:"varint,4,opt,name=include_transactions,json=includeTransactions,proto3" json:"include_transactions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlockRequest) GetChain() *ChainSelector {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *GetBlockRequest) GetBlockRef() isGetBlockRequest_BlockRef {
	if x != nil {
		return x.BlockRef
	}
	return nil
}

func (x *GetBlockRequest) GetHash() string {
	if x != nil {
		if x, ok := x.BlockRef.(*GetBlockRequest_Hash); ok {
			return x.Hash
		}
	}
	return ""
}

func (x *GetBlockRequest) GetHeight() uint64 {
	if x != nil {
		if x, ok := x.BlockRef.(*GetBlockRequest_Height); ok {
			return x.Height
		}
	}
	return 0
}

func (x *GetBlockRequest) GetIncludeTransactions() bool {
	if x != nil {
		return x.IncludeTransactions
	}
	return false
}

type isGetBlockRequest_BlockRef interface {
	isGetBlockRequest_BlockRef()
}

type GetBlockRequest_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

type GetBlockRequest_Height struct {
	Height uint64 `protobuf:"varint,3,opt,name=height,proto3,oneof"`
}

func (*GetBlockRequest_Hash) isGetBlockRequest_BlockRef() {}

func (*GetBlockRequest_Height) isGetBlockRequest_BlockRef() {}

type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type ListBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         *ChainSelector         `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Paging        *BlocksPagination      `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{13}
}

func (x *ListBlocksRequest) GetChain() *ChainSelector {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *ListBlocksRequest) GetPaging() *BlocksPagination {
	if x != nil {
		return x.Paging
	}
	return nil
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockSummary        `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{14}
}

func (x *ListBlocksResponse) GetBlocks() []*BlockSummary {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         *ChainSelector         `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Txid          string                 `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransactionRequest) GetChain() *ChainSelector {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *GetTransactionRequest) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetAddressBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         *ChainSelector         `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressBalanceRequest) Reset() {
	*x = GetAddressBalanceRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressBalanceRequest) ProtoMessage() {}

func (x *GetAddressBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetAddressBalanceRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{17}
}

func (x *GetAddressBalanceRequest) GetChain() *ChainSelector {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *GetAddressBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetAddressBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *AddressBalance        `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressBalanceResponse) Reset() {
	*x = GetAddressBalanceResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressBalanceResponse) ProtoMessage() {}

func (x *GetAddressBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetAddressBalanceResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{18}
}

func (x *GetAddressBalanceResponse) GetBalance() *AddressBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ListAddressTransactionsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Chain         *ChainSelector          `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Address       string                  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Paging        *TransactionsPagination `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressTransactionsRequest) Reset() {
	*x = ListAddressTransactionsRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressTransactionsRequest) ProtoMessage() {}

func (x *ListAddressTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListAddressTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{19}
}

func (x *ListAddressTransactionsRequest) GetChain() *ChainSelector {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *ListAddressTransactionsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListAddressTransactionsRequest) GetPaging() *TransactionsPagination {
	if x != nil {
		return x.Paging
	}
	return nil
}

type ListAddressTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionSummary  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressTransactionsResponse) Reset() {
	*x = ListAddressTransactionsResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressTransactionsResponse) ProtoMessage() {}

func (x *ListAddressTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListAddressTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{20}
}

func (x *ListAddressTransactionsResponse) GetTransactions() []*TransactionSummary {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         *ChainSelector         `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{21}
}

func (x *HealthRequest) GetChain() *ChainSelector {
	if x != nil {
		return x.Chain
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=blockinsight7000.v1.HealthStatus" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{22}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// BlocksPagination uses a block height cursor to page through block lists.
type BlocksPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	CursorHeight  uint64                 `protobuf:"varint,2,opt,name=cursor_height,json=cursorHeight,proto3" json:"cursor_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlocksPagination) Reset() {
	*x = BlocksPagination{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlocksPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksPagination) ProtoMessage() {}

func (x *BlocksPagination) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksPagination.ProtoReflect.Descriptor instead.
func (*BlocksPagination) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{23}
}

func (x *BlocksPagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BlocksPagination) GetCursorHeight() uint64 {
	if x != nil {
		return x.CursorHeight
	}
	return 0
}

// TransactionsPagination uses a transaction hash cursor for address history.
type TransactionsPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	CursorTxid    string                 `protobuf:"bytes,2,opt,name=cursor_txid,json=cursorTxid,proto3" json:"cursor_txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsPagination) Reset() {
	*x = TransactionsPagination{}
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsPagination) ProtoMessage() {}

func (x *TransactionsPagination) ProtoReflect() protoreflect.Message {
	mi := &file_blockinsight7000_v1_explorer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsPagination.ProtoReflect.Descriptor instead.
func (*TransactionsPagination) Descriptor() ([]byte, []int) {
	return file_blockinsight7000_v1_explorer_proto_rawDescGZIP(), []int{24}
}

func (x *TransactionsPagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TransactionsPagination) GetCursorTxid() string {
	if x != nil {
		return x.CursorTxid
	}
	return ""
}

var File_blockinsight7000_v1_explorer_proto protoreflect.FileDescriptor

const file_blockinsight7000_v1_explorer_proto_rawDesc = "" +
	"\n" +
	"\"blockinsight7000/v1/explorer.proto\x12\x13blockinsight7000.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a blockinsight7000/v1/common.proto\"\xbd\x01\n" +
	"\fBlockSummary\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x125\n" +
	"\bmined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aminedAt\x12+\n" +
	"\x11transaction_count\x18\x04 \x01(\rR\x10transactionCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\"\xaa\x03\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\tR\fpreviousHash\x12\x1f\n" +
	"\vmerkle_root\x18\x04 \x01(\tR\n" +
	"merkleRoot\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x04R\n" +
	"difficulty\x12$\n" +
	"\rconfirmations\x18\b \x01(\rR\rconfirmations\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\t \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\x04R\x06weight\x125\n" +
	"\bmined_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aminedAt\x12K\n" +
	"\ftransactions\x18\f \x03(\v2'.blockinsight7000.v1.TransactionSummaryR\ftransactions\"\xbd\x01\n" +
	"\x12TransactionSummary\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12$\n" +
	"\rconfirmations\x18\x02 \x01(\rR\rconfirmations\x12\x1d\n" +
	"\n" +
	"total_sats\x18\x03 \x01(\x04R\ttotalSats\x12\x19\n" +
	"\bfee_sats\x18\x04 \x01(\x04R\afeeSats\x123\n" +
	"\aseen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06seenAt\"\xc6\x01\n" +
	"\x10TransactionInput\x12\x1b\n" +
	"\tprev_txid\x18\x01 \x01(\tR\bprevTxid\x12!\n" +
	"\foutput_index\x18\x02 \x01(\rR\voutputIndex\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"value_sats\x18\x04 \x01(\x04R\tvalueSats\x12\x1d\n" +
	"\n" +
	"script_sig\x18\x05 \x01(\fR\tscriptSig\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\rR\bsequence\"\x9e\x01\n" +
	"\x11TransactionOutput\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"value_sats\x18\x03 \x01(\x04R\tvalueSats\x12\x14\n" +
	"\x05spent\x18\x04 \x01(\bR\x05spent\x12$\n" +
	"\x0escript_pub_key\x18\x05 \x01(\fR\fscriptPubKey\"\xe3\x02\n" +
	"\vTransaction\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x1b\n" +
	"\tlock_time\x18\x04 \x01(\rR\blockTime\x12$\n" +
	"\rconfirmations\x18\x05 \x01(\rR\rconfirmations\x12\x19\n" +
	"\bfee_sats\x18\x06 \x01(\x04R\afeeSats\x123\n" +
	"\aseen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06seenAt\x12=\n" +
	"\x06inputs\x18\b \x03(\v2%.blockinsight7000.v1.TransactionInputR\x06inputs\x12@\n" +
	"\aoutputs\x18\t \x03(\v2&.blockinsight7000.v1.TransactionOutputR\aoutputs\"\xd4\x01\n" +
	"\x0eAddressBalance\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x0econfirmed_sats\x18\x02 \x01(\x04R\rconfirmedSats\x12)\n" +
	"\x10unconfirmed_sats\x18\x03 \x01(\x04R\x0funconfirmedSats\x12.\n" +
	"\x13total_received_sats\x18\x04 \x01(\x04R\x11totalReceivedSats\x12&\n" +
	"\x0ftotal_sent_sats\x18\x05 \x01(\x04R\rtotalSentSats\"m\n" +
	"\x0fNetworkMetadata\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\"\x88\x01\n" +
	"\rChainMetadata\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12@\n" +
	"\bnetworks\x18\x03 \x03(\v2$.blockinsight7000.v1.NetworkMetadataR\bnetworks\"\x13\n" +
	"\x11ListChainsRequest\"P\n" +
	"\x12ListChainsResponse\x12:\n" +
	"\x06chains\x18\x01 \x03(\v2\".blockinsight7000.v1.ChainMetadataR\x06chains\"\xbb\x01\n" +
	"\x0fGetBlockRequest\x128\n" +
	"\x05chain\x18\x01 \x01(\v2\".blockinsight7000.v1.ChainSelectorR\x05chain\x12\x14\n" +
	"\x04hash\x18\x02 \x01(\tH\x00R\x04hash\x12\x18\n" +
	"\x06height\x18\x03 \x01(\x04H\x00R\x06height\x121\n" +
	"\x14include_transactions\x18\x04 \x01(\bR\x13includeTransactionsB\v\n" +
	"\tblock_ref\"D\n" +
	"\x10GetBlockResponse\x120\n" +
	"\x05block\x18\x01 \x01(\v2\x1a.blockinsight7000.v1.BlockR\x05block\"\x8c\x01\n" +
	"\x11ListBlocksRequest\x128\n" +
	"\x05chain\x18\x01 \x01(\v2\".blockinsight7000.v1.ChainSelectorR\x05chain\x12=\n" +
	"\x06paging\x18\x02 \x01(\v2%.blockinsight7000.v1.BlocksPaginationR\x06paging\"O\n" +
	"\x12ListBlocksResponse\x129\n" +
	"\x06blocks\x18\x01 \x03(\v2!.blockinsight7000.v1.BlockSummaryR\x06blocks\"e\n" +
	"\x15GetTransactionRequest\x128\n" +
	"\x05chain\x18\x01 \x01(\v2\".blockinsight7000.v1.ChainSelectorR\x05chain\x12\x12\n" +
	"\x04txid\x18\x02 \x01(\tR\x04txid\"\\\n" +
	"\x16GetTransactionResponse\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2 .blockinsight7000.v1.TransactionR\vtransaction\"n\n" +
	"\x18GetAddressBalanceRequest\x128\n" +
	"\x05chain\x18\x01 \x01(\v2\".blockinsight7000.v1.ChainSelectorR\x05chain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"Z\n" +
	"\x19GetAddressBalanceResponse\x12=\n" +
	"\abalance\x18\x01 \x01(\v2#.blockinsight7000.v1.AddressBalanceR\abalance\"\xb9\x01\n" +
	"\x1eListAddressTransactionsRequest\x128\n" +
	"\x05chain\x18\x01 \x01(\v2\".blockinsight7000.v1.ChainSelectorR\x05chain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12C\n" +
	"\x06paging\x18\x03 \x01(\v2+.blockinsight7000.v1.TransactionsPaginationR\x06paging\"n\n" +
	"\x1fListAddressTransactionsResponse\x12K\n" +
	"\ftransactions\x18\x01 \x03(\v2'.blockinsight7000.v1.TransactionSummaryR\ftransactions\"I\n" +
	"\rHealthRequest\x128\n" +
	"\x05chain\x18\x01 \x01(\v2\".blockinsight7000.v1.ChainSelectorR\x05chain\"m\n" +
	"\x0eHealthResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.blockinsight7000.v1.HealthStatusR\x06status\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"M\n" +
	"\x10BlocksPagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12#\n" +
	"\rcursor_height\x18\x02 \x01(\x04R\fcursorHeight\"O\n" +
	"\x16TransactionsPagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x1f\n" +
	"\vcursor_txid\x18\x02 \x01(\tR\n" +
	"cursorTxid2\xb5\n" +
	"\n" +
	"\x0fExplorerService\x12\x96\x01\n" +
	"\x06Health\x12\".blockinsight7000.v1.HealthRequest\x1a#.blockinsight7000.v1.HealthResponse\"C\x82\xd3\xe4\x93\x02=\x12;/api/v1/chains/{chain.coin}/networks/{chain.network}/health\x12u\n" +
	"\n" +
	"ListChains\x12&.blockinsight7000.v1.ListChainsRequest\x1a'.blockinsight7000.v1.ListChainsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/chains\x12\xa2\x01\n" +
	"\n" +
	"ListBlocks\x12&.blockinsight7000.v1.ListBlocksRequest\x1a'.blockinsight7000.v1.ListBlocksResponse\"C\x82\xd3\xe4\x93\x02=\x12;/api/v1/chains/{chain.coin}/networks/{chain.network}/blocks\x12\xf9\x01\n" +
	"\bGetBlock\x12$.blockinsight7000.v1.GetBlockRequest\x1a%.blockinsight7000.v1.GetBlockResponse\"\x9f\x01\x82\xd3\xe4\x93\x02\x98\x01ZM\x12K/api/v1/chains/{chain.coin}/networks/{chain.network}/blocks/height/{height}\x12G/api/v1/chains/{chain.coin}/networks/{chain.network}/blocks/hash/{hash}\x12\xbb\x01\n" +
	"\x0eGetTransaction\x12*.blockinsight7000.v1.GetTransactionRequest\x1a+.blockinsight7000.v1.GetTransactionResponse\"P\x82\xd3\xe4\x93\x02J\x12H/api/v1/chains/{chain.coin}/networks/{chain.network}/transactions/{txid}\x12\xcc\x01\n" +
	"\x11GetAddressBalance\x12-.blockinsight7000.v1.GetAddressBalanceRequest\x1a..blockinsight7000.v1.GetAddressBalanceResponse\"X\x82\xd3\xe4\x93\x02R\x12P/api/v1/chains/{chain.coin}/networks/{chain.network}/addresses/{address}/balance\x12\xe3\x01\n" +
	"\x17ListAddressTransactions\x123.blockinsight7000.v1.ListAddressTransactionsRequest\x1a4.blockinsight7000.v1.ListAddressTransactionsResponse\"]\x82\xd3\xe4\x93\x02W\x12U/api/v1/chains/{chain.coin}/networks/{chain.network}/addresses/{address}/transactionsBaZ_github.com/goodnatureofminers/blockinsight7000-proto/pkg/blockinsight7000/v1;blockinsight7000v1b\x06proto3"

var (
	file_blockinsight7000_v1_explorer_proto_rawDescOnce sync.Once
	file_blockinsight7000_v1_explorer_proto_rawDescData []byte
)

func file_blockinsight7000_v1_explorer_proto_rawDescGZIP() []byte {
	file_blockinsight7000_v1_explorer_proto_rawDescOnce.Do(func() {
		file_blockinsight7000_v1_explorer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockinsight7000_v1_explorer_proto_rawDesc), len(file_blockinsight7000_v1_explorer_proto_rawDesc)))
	})
	return file_blockinsight7000_v1_explorer_proto_rawDescData
}

var file_blockinsight7000_v1_explorer_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_blockinsight7000_v1_explorer_proto_goTypes = []any{
	(*BlockSummary)(nil),                    // 0: blockinsight7000.v1.BlockSummary
	(*Block)(nil),                           // 1: blockinsight7000.v1.Block
	(*TransactionSummary)(nil),              // 2: blockinsight7000.v1.TransactionSummary
	(*TransactionInput)(nil),                // 3: blockinsight7000.v1.TransactionInput
	(*TransactionOutput)(nil),               // 4: blockinsight7000.v1.TransactionOutput
	(*Transaction)(nil),                     // 5: blockinsight7000.v1.Transaction
	(*AddressBalance)(nil),                  // 6: blockinsight7000.v1.AddressBalance
	(*NetworkMetadata)(nil),                 // 7: blockinsight7000.v1.NetworkMetadata
	(*ChainMetadata)(nil),                   // 8: blockinsight7000.v1.ChainMetadata
	(*ListChainsRequest)(nil),               // 9: blockinsight7000.v1.ListChainsRequest
	(*ListChainsResponse)(nil),              // 10: blockinsight7000.v1.ListChainsResponse
	(*GetBlockRequest)(nil),                 // 11: blockinsight7000.v1.GetBlockRequest
	(*GetBlockResponse)(nil),                // 12: blockinsight7000.v1.GetBlockResponse
	(*ListBlocksRequest)(nil),               // 13: blockinsight7000.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),              // 14: blockinsight7000.v1.ListBlocksResponse
	(*GetTransactionRequest)(nil),           // 15: blockinsight7000.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),          // 16: blockinsight7000.v1.GetTransactionResponse
	(*GetAddressBalanceRequest)(nil),        // 17: blockinsight7000.v1.GetAddressBalanceRequest
	(*GetAddressBalanceResponse)(nil),       // 18: blockinsight7000.v1.GetAddressBalanceResponse
	(*ListAddressTransactionsRequest)(nil),  // 19: blockinsight7000.v1.ListAddressTransactionsRequest
	(*ListAddressTransactionsResponse)(nil), // 20: blockinsight7000.v1.ListAddressTransactionsResponse
	(*HealthRequest)(nil),                   // 21: blockinsight7000.v1.HealthRequest
	(*HealthResponse)(nil),                  // 22: blockinsight7000.v1.HealthResponse
	(*BlocksPagination)(nil),                // 23: blockinsight7000.v1.BlocksPagination
	(*TransactionsPagination)(nil),          // 24: blockinsight7000.v1.TransactionsPagination
	(*timestamppb.Timestamp)(nil),           // 25: google.protobuf.Timestamp
	(*ChainSelector)(nil),                   // 26: blockinsight7000.v1.ChainSelector
	(HealthStatus)(0),                       // 27: blockinsight7000.v1.HealthStatus
}
var file_blockinsight7000_v1_explorer_proto_depIdxs = []int32{
	25, // 0: blockinsight7000.v1.BlockSummary.mined_at:type_name -> google.protobuf.Timestamp
	25, // 1: blockinsight7000.v1.Block.mined_at:type_name -> google.protobuf.Timestamp
	2,  // 2: blockinsight7000.v1.Block.transactions:type_name -> blockinsight7000.v1.TransactionSummary
	25, // 3: blockinsight7000.v1.TransactionSummary.seen_at:type_name -> google.protobuf.Timestamp
	25, // 4: blockinsight7000.v1.Transaction.seen_at:type_name -> google.protobuf.Timestamp
	3,  // 5: blockinsight7000.v1.Transaction.inputs:type_name -> blockinsight7000.v1.TransactionInput
	4,  // 6: blockinsight7000.v1.Transaction.outputs:type_name -> blockinsight7000.v1.TransactionOutput
	7,  // 7: blockinsight7000.v1.ChainMetadata.networks:type_name -> blockinsight7000.v1.NetworkMetadata
	8,  // 8: blockinsight7000.v1.ListChainsResponse.chains:type_name -> blockinsight7000.v1.ChainMetadata
	26, // 9: blockinsight7000.v1.GetBlockRequest.chain:type_name -> blockinsight7000.v1.ChainSelector
	1,  // 10: blockinsight7000.v1.GetBlockResponse.block:type_name -> blockinsight7000.v1.Block
	26, // 11: blockinsight7000.v1.ListBlocksRequest.chain:type_name -> blockinsight7000.v1.ChainSelector
	23, // 12: blockinsight7000.v1.ListBlocksRequest.paging:type_name -> blockinsight7000.v1.BlocksPagination
	0,  // 13: blockinsight7000.v1.ListBlocksResponse.blocks:type_name -> blockinsight7000.v1.BlockSummary
	26, // 14: blockinsight7000.v1.GetTransactionRequest.chain:type_name -> blockinsight7000.v1.ChainSelector
	5,  // 15: blockinsight7000.v1.GetTransactionResponse.transaction:type_name -> blockinsight7000.v1.Transaction
	26, // 16: blockinsight7000.v1.GetAddressBalanceRequest.chain:type_name -> blockinsight7000.v1.ChainSelector
	6,  // 17: blockinsight7000.v1.GetAddressBalanceResponse.balance:type_name -> blockinsight7000.v1.AddressBalance
	26, // 18: blockinsight7000.v1.ListAddressTransactionsRequest.chain:type_name -> blockinsight7000.v1.ChainSelector
	24, // 19: blockinsight7000.v1.ListAddressTransactionsRequest.paging:type_name -> blockinsight7000.v1.TransactionsPagination
	2,  // 20: blockinsight7000.v1.ListAddressTransactionsResponse.transactions:type_name -> blockinsight7000.v1.TransactionSummary
	26, // 21: blockinsight7000.v1.HealthRequest.chain:type_name -> blockinsight7000.v1.ChainSelector
	27, // 22: blockinsight7000.v1.HealthResponse.status:type_name -> blockinsight7000.v1.HealthStatus
	21, // 23: blockinsight7000.v1.ExplorerService.Health:input_type -> blockinsight7000.v1.HealthRequest
	9,  // 24: blockinsight7000.v1.ExplorerService.ListChains:input_type -> blockinsight7000.v1.ListChainsRequest
	13, // 25: blockinsight7000.v1.ExplorerService.ListBlocks:input_type -> blockinsight7000.v1.ListBlocksRequest
	11, // 26: blockinsight7000.v1.ExplorerService.GetBlock:input_type -> blockinsight7000.v1.GetBlockRequest
	15, // 27: blockinsight7000.v1.ExplorerService.GetTransaction:input_type -> blockinsight7000.v1.GetTransactionRequest
	17, // 28: blockinsight7000.v1.ExplorerService.GetAddressBalance:input_type -> blockinsight7000.v1.GetAddressBalanceRequest
	19, // 29: blockinsight7000.v1.ExplorerService.ListAddressTransactions:input_type -> blockinsight7000.v1.ListAddressTransactionsRequest
	22, // 30: blockinsight7000.v1.ExplorerService.Health:output_type -> blockinsight7000.v1.HealthResponse
	10, // 31: blockinsight7000.v1.ExplorerService.ListChains:output_type -> blockinsight7000.v1.ListChainsResponse
	14, // 32: blockinsight7000.v1.ExplorerService.ListBlocks:output_type -> blockinsight7000.v1.ListBlocksResponse
	12, // 33: blockinsight7000.v1.ExplorerService.GetBlock:output_type -> blockinsight7000.v1.GetBlockResponse
	16, // 34: blockinsight7000.v1.ExplorerService.GetTransaction:output_type -> blockinsight7000.v1.GetTransactionResponse
	18, // 35: blockinsight7000.v1.ExplorerService.GetAddressBalance:output_type -> blockinsight7000.v1.GetAddressBalanceResponse
	20, // 36: blockinsight7000.v1.ExplorerService.ListAddressTransactions:output_type -> blockinsight7000.v1.ListAddressTransactionsResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_blockinsight7000_v1_explorer_proto_init() }
func file_blockinsight7000_v1_explorer_proto_init() {
	if File_blockinsight7000_v1_explorer_proto != nil {
		return
	}
	file_blockinsight7000_v1_common_proto_init()
	file_blockinsight7000_v1_explorer_proto_msgTypes[11].OneofWrappers = []any{
		(*GetBlockRequest_Hash)(nil),
		(*GetBlockRequest_Height)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockinsight7000_v1_explorer_proto_rawDesc), len(file_blockinsight7000_v1_explorer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blockinsight7000_v1_explorer_proto_goTypes,
		DependencyIndexes: file_blockinsight7000_v1_explorer_proto_depIdxs,
		MessageInfos:      file_blockinsight7000_v1_explorer_proto_msgTypes,
	}.Build()
	File_blockinsight7000_v1_explorer_proto = out.File
	file_blockinsight7000_v1_explorer_proto_goTypes = nil
	file_blockinsight7000_v1_explorer_proto_depIdxs = nil
}
